services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54326:5432"
    environment:
      POSTGRES_USER: tanawat
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tanawat
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: 69-s3-admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tanawat-chi@rmutp.ac.th
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: my_app
    ports:
      - "8080:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: tanawat
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: tanawat
      DATABASE_PASSWORD: 1234
    depends_on:
      - db

volumes:
  postgres_data: