services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - "54326:5432"
    environment:
      - POSTGRES_USER=tanawat
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tanawat
